### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by joe1206** [KeiKinn/StickerOnScreen#2]
怎么挂梯子才能刷新，不挂就无效自变量，怎么解决

**Comment by KeiKinn** [comment]
目前图片是托管在github仓库，因此暂时没有什么更好的解决办法，不过可以探索一下。

**Comment by KeiKinn** [comment]
可以把仓库转移到国内的代码托管平台，比如码云

**Comment by joe1206** [comment]
嗯嗯好的，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JingX <notifications@github.com&gt;
发送时间: 2021年1月11日 12:45
收件人: KeiKinn/StickerOnScreen <StickerOnScreen@noreply.github.com&gt;
抄送: JoeSmith <1426568561@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[KeiKinn/StickerOnScreen] 显示问题 (#2)

**Comment by joe1206** [comment]
大佬，我转到码云了，改了URL连接，还是不行啊，提示Error:cannot parse response to an image
这是我改的，网址在这
https://gitee.com/joesmith1206/StickerOnScreen/blob/main/src/StickerOnScreen.js

这个咋解决，是别的地方也要改啥吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KeiKinn/StickerOnScreen"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 中午12:45
收件人:&nbsp;"KeiKinn/StickerOnScreen"<StickerOnScreen@noreply.github.com&gt;;
抄送:&nbsp;"南极不下雪"<1426568561@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [KeiKinn/StickerOnScreen] 显示问题 (#2)





 
可以把仓库转移到国内的代码托管平台，比如码云

**Comment by joe1206** [comment]
好了，我自己改好了，感谢大佬的源码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KeiKinn/StickerOnScreen"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 中午12:45
收件人:&nbsp;"KeiKinn/StickerOnScreen"<StickerOnScreen@noreply.github.com&gt;;
抄送:&nbsp;"南极不下雪"<1426568561@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [KeiKinn/StickerOnScreen] 显示问题 (#2)





 
可以把仓库转移到国内的代码托管平台，比如码云

**Comment by KeiKinn** [comment]
很高兴你改好了。

虽然是开源的代码，还是希望你能在码云上添加指向本项目的链接。

**Comment by joe1206** [comment]
嗯嗯好的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JingX <notifications@github.com&gt;
发送时间: 2021年1月11日 21:07
收件人: KeiKinn/StickerOnScreen <StickerOnScreen@noreply.github.com&gt;
抄送: JoeSmith <1426568561@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[KeiKinn/StickerOnScreen] 显示问题 (#2)





 
很高兴你改好了。
 
虽然是开源的代码，还是希望你能在码云上添加指向本项目的链接。
