### ISSUE TITLE
关于这个JS有点疑问❓

### ISSUE THREAD

**Issue by lzr52o** [KeiKinn/StickerOnScreen#3]
大佬这个必须开VPN翻墙才能用吗？我的QuantumultX关了它就错误不显示了

**Comment by KeiKinn** [comment]
是的，因为图片是保存在GitHub上的，有朋友已经将项目转移到了gitgee，具体请见：https://gitee.com/joesmith1206/StickerOnScreen/blob/main/src/StickerOnScreen.js

gitgee是国内平台，应该不存在这个问题。

祝好
