### ISSUE TITLE
我有一个小问题

### ISSUE THREAD

**Issue by eielyving** [KeiKinn/StickerOnScreen#4]
你好，这个StickerOnScreen非常好用我很喜欢！
但是之前出现了一点小问题，手机必须挂着vpn才能不让贴纸失效，我完全不懂组件内容逻辑，不知道怎么办
还有我想怎么能添加自己的相册中的贴纸图片，这样就更方便了。里面的图片地址我完全不懂怎么改哈哈哈~
冒昧打扰了，如果可以，您可以回复邮箱  eielyving@gmail.com 和我联系

**Comment by KeiKinn** [comment]
1. 有位朋友已经将该项目托管至国内的[码云平台](https://gitee.com/joesmith1206/StickerOnScreen/blob/main/src/StickerOnScreen.js)，这可以解决VPN的问题；
2. 现在的逻辑是访问该仓库中image中的图片资源，暂时并没有访问本地图片的能力，如果你希望添加自己的图片，最简单的办法就是fork码云上的仓库，并按照Stickers文件夹的文件命名方式命名你的图片（保持1000为起始序号即可），同时将[主文件中const stickerSum = xxx;](https://github.com/KeiKinn/StickerOnScreen/blob/13d51c108dc876d9da986b9c1a7dc08b3c6b3e09/src/StickerOnScreen.js#L85)的数字改为Stickers文件夹中文件的总数量即可。

**Comment by eielyving** [comment]
感谢您的回复
我操作了好长时间，终于把我的弄出来了。但是结果还是感觉哪里不太对？
我fork了码云上的仓库，重新命名，总数量也改了，结果发现还是七濑胡桃。
然后把源文件的地址imgUrl 改成我的地址
（按他上面的扒了下来https://gitee.com/joesmith1206/StickerOnScreen/**raw**/main/Stickers/Sticker_， 
其中只有raw不一样，我的地址里面没有“raw”、我也把tree和下面的blog改成了raw，不知道会不会出问题）
然后在手机运行结果开不开VPN都很不稳定，只成功过一次透明背景。后来就变成"Error: cannot parese response to an image"的提示，而不开透明背景则没有问题。
我试了一下那位朋友的，没有出现我这样的问题，不开代理也可以很好的运行，说明不是网络还是我的操作有问题吗？
我就是在网页上修改的，没有GitHub那种本地仓库
我实在是不知道什么原因才回来麻烦你看一下，这是我弄的新的那个
[https://gitee.com/hanfengfacai/StickerOnScreen/blob/main/src/StickerOnScreen.js](url)
实在不好意思麻烦你，我弄了好长时间没玩明白哈哈哈，
中秋快乐~

**Comment by KeiKinn** [comment]
1. 你对地址的修改是正确的，我疏忽了，raw一般代表的是文件的原始存储；
2. 因为我没有gitgee的账号，根据错误提示应该是访问链接时返回的不是正确的，你可以尝试通过直接在浏览器访问https://gitee.com/hanfengfacai/StickerOnScreen/raw/main/Stickers/Sticker_10xx.png 看看是否能正常加载图片

**Comment by eielyving** [comment]
我成功啦
找到原因是因为gitee图床超过1M只能登陆后可见，这奇怪的设定导致那个问题，没办法我只能压缩后重新上传就解决了
感谢帮助~
你是在国外是吧，我说都两点了程序员也没这么能熬啊
再次感谢，中秋快乐，顺颂时祺

**Comment by KeiKinn** [comment]
恭喜，你解决问题的能力也非常棒！希望你用的愉快，也可以多多给朋友们推荐。

国内平台是总有一些奇奇怪怪的问题。

中秋快乐

**Comment by eielyving** [comment]
哥，我设置大号尺寸的小部件为什么感觉和小号的差不多大，旁边空了好大一块这东西能调么，还是设置的问题？我现在是iPhoneXs这有关系吗

**Comment by KeiKinn** [comment]
与设备无关; 

图片尺寸可以试着调整https://github.com/KeiKinn/StickerOnScreen/blob/13d51c108dc876d9da986b9c1a7dc08b3c6b3e09/src/StickerOnScreen.js#L94

width 和 height建议相同

需要注意的是最终呈现的尺寸有多个因素影响，甚至是原图片的尺寸。

**Comment by eielyving** [comment]
很棒！大号可以变大，可是小号也相应的变大了，我大小号组件分别有一个，看来只能再建一个仓库存大号组件了呢
麻烦你啦

**Comment by KeiKinn** [comment]
> 很棒！大号可以变大，可是小号也相应的变大了，我大小号组件分别有一个，看来只能再建一个仓库存大号组件了呢
> 麻烦你啦

你不需要重新创建一个仓库，scriptable 可以在本地修改程序，并不会影响到你在gitgee的内容，因此，可以在scriptable中再创建一个不同名，但是内容相同的程序（比如叫larger_size_xxxx），一个负责中号部件，一个负责大号部件

**Comment by eielyving** [comment]
搞定！我在仓库又建了一个sticker2用新的图片。
对了你的stickers是在pixiv上弄的吗，还是其他资源啊，我好像看到了几个这种立绘
，反正我这里应该不会再有问题了，哈哈哈这么麻烦你我都不好意思了。

**Comment by KeiKinn** [comment]
stickers是line的表情贴纸，其他的就是网络资源了
