### ISSUE TITLE
还得麻烦一下

### ISSUE THREAD

**Issue by eielyving** [KeiKinn/StickerOnScreen#5]
哥我上回发的你可能没看到
我这还有一个小问题，就是设置大号组件后stickers还是显示的小图，只不过旁边的空白处大了
怎么能让图变大呢？
您有空时候回一下

**Comment by KeiKinn** [comment]
https://github.com/KeiKinn/StickerOnScreen/issues/4#issuecomment-924820892

**Comment by KeiKinn** [comment]
https://github.com/KeiKinn/StickerOnScreen/issues/4#issuecomment-926422702
