### ISSUE TITLE
关掉vpn，或者没网时组件变白

### ISSUE THREAD

**Issue by chengkongyiban** [KeiKinn/StickerOnScreen#6]
能否改成，关掉vpn或者断网时显示最近一次使用的图片。

**Comment by KeiKinn** [comment]
可以使用这位朋友fork在gitgee的仓库https://github.com/KeiKinn/StickerOnScreen/issues/4#issuecomment-922967521

断网之后的显示，最近可能并没有精力，抱歉

**Comment by chengkongyiban** [comment]
感谢回答
